version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
formats:
  - htmlzip
  - pdf
  - epub
python:
  install:
    - requirements: docs/requirements.txt
mkdocs:  # Gunakan MkDocs untuk Markdown
  configuration: mkdocs.yml